modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Permissions/issues"

[[mods]]
    modId="project_essentials_permissions"
    version="1.15.2-1.0.2"
    displayName="Project Essentials Permissions"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Permissions/MC-1.15.2/update.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Permissions"
    credits="Thanks JetBrains for Intellij IDEA license!"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Project Essentials Permissions - additional module for Essentials;
    Just controlling player permissions.

    Also it just permission API for forge.
    '''

[[dependencies.project_essentials_permissions]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_permissions]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_permissions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
