modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Permissions/issues"

[[mods]]
    modId="project_essentials_permissions"
    version="${file.jarVersion}"
    displayName="Project Essentials Permissions"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Permissions/MC-1.14.X/updatev2.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Permissions"
    credits="hujle, JetBrains, all forge developers, and other contributors"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Module of Project Essentials. API for working with players permissions,
    controlling the in-world actions of players.
    '''

[[dependencies.project_essentials_permissions]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_permissions]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_permissions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
